//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/New Input System/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""10d323a8-0e4f-4472-9f68-0beb5b35a018"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d3be3d06-f3c8-42ba-b382-5425bb7064c8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetItem"",
                    ""type"": ""Button"",
                    ""id"": ""5ddacc4c-d2d3-4cf4-8c6f-b159fefd2c3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCameraLeft"",
                    ""type"": ""Button"",
                    ""id"": ""9e9c7aae-b590-4c4b-8096-87abf0c7dc65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCameraRight"",
                    ""type"": ""Button"",
                    ""id"": ""788cd556-75c8-453e-84e1-f780fdc16c05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SizeCameraUp"",
                    ""type"": ""Button"",
                    ""id"": ""5486f5f2-0b7e-4b08-bf29-537268a6abaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SizeCameraDown"",
                    ""type"": ""Button"",
                    ""id"": ""b81264e3-da9f-40b7-8052-68cb25db7880"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""5135ee9a-62be-444a-b84e-ebc4fe2b300e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Nextphrase"",
                    ""type"": ""Button"",
                    ""id"": ""d28357d3-49d5-44b8-a2e8-de87395bf470"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SitDown"",
                    ""type"": ""Button"",
                    ""id"": ""a90d9ace-3f8b-430c-8b7c-4e3a020ec4ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""294feecc-85e5-4485-824d-5fa673c67efe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6f02b48f-6104-4534-a9a3-ac815f4b6d52"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d92301ac-e1ab-456f-8ba6-a8160f1c6da4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7f57bbad-822b-4ff9-a4cb-56b02ecbfd43"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""376eae34-144f-4910-800b-174c73e3e636"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""28b73c8a-6b92-4237-9058-8d247307044b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2fc896c-58c1-4a3b-b084-2719b48a7245"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCameraLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""075a882f-a61a-4eda-85c0-eecee455cd33"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCameraRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""864bf80e-c17e-4b88-b499-08f7b6408242"",
                    ""path"": ""<Keyboard>/equals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SizeCameraUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09d40bb7-e82b-49f0-999c-67260daa88cb"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SizeCameraDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f162b137-271c-4e90-91cc-fa8de3f92999"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2c1620b-8ba1-4af9-b727-2d4289578834"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Nextphrase"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0159b95-5a4d-4af9-ab52-3c45110c00f0"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SitDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_GetItem = m_Player.FindAction("GetItem", throwIfNotFound: true);
        m_Player_RotateCameraLeft = m_Player.FindAction("RotateCameraLeft", throwIfNotFound: true);
        m_Player_RotateCameraRight = m_Player.FindAction("RotateCameraRight", throwIfNotFound: true);
        m_Player_SizeCameraUp = m_Player.FindAction("SizeCameraUp", throwIfNotFound: true);
        m_Player_SizeCameraDown = m_Player.FindAction("SizeCameraDown", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_Nextphrase = m_Player.FindAction("Nextphrase", throwIfNotFound: true);
        m_Player_SitDown = m_Player.FindAction("SitDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_GetItem;
    private readonly InputAction m_Player_RotateCameraLeft;
    private readonly InputAction m_Player_RotateCameraRight;
    private readonly InputAction m_Player_SizeCameraUp;
    private readonly InputAction m_Player_SizeCameraDown;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_Nextphrase;
    private readonly InputAction m_Player_SitDown;
    public struct PlayerActions
    {
        private @PlayerAction m_Wrapper;
        public PlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @GetItem => m_Wrapper.m_Player_GetItem;
        public InputAction @RotateCameraLeft => m_Wrapper.m_Player_RotateCameraLeft;
        public InputAction @RotateCameraRight => m_Wrapper.m_Player_RotateCameraRight;
        public InputAction @SizeCameraUp => m_Wrapper.m_Player_SizeCameraUp;
        public InputAction @SizeCameraDown => m_Wrapper.m_Player_SizeCameraDown;
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @Nextphrase => m_Wrapper.m_Player_Nextphrase;
        public InputAction @SitDown => m_Wrapper.m_Player_SitDown;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @GetItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetItem;
                @GetItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetItem;
                @GetItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetItem;
                @RotateCameraLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraLeft;
                @RotateCameraLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraLeft;
                @RotateCameraLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraLeft;
                @RotateCameraRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraRight;
                @RotateCameraRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraRight;
                @RotateCameraRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCameraRight;
                @SizeCameraUp.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraUp;
                @SizeCameraUp.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraUp;
                @SizeCameraUp.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraUp;
                @SizeCameraDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraDown;
                @SizeCameraDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraDown;
                @SizeCameraDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSizeCameraDown;
                @Run.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Nextphrase.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNextphrase;
                @Nextphrase.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNextphrase;
                @Nextphrase.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnNextphrase;
                @SitDown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSitDown;
                @SitDown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSitDown;
                @SitDown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSitDown;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @GetItem.started += instance.OnGetItem;
                @GetItem.performed += instance.OnGetItem;
                @GetItem.canceled += instance.OnGetItem;
                @RotateCameraLeft.started += instance.OnRotateCameraLeft;
                @RotateCameraLeft.performed += instance.OnRotateCameraLeft;
                @RotateCameraLeft.canceled += instance.OnRotateCameraLeft;
                @RotateCameraRight.started += instance.OnRotateCameraRight;
                @RotateCameraRight.performed += instance.OnRotateCameraRight;
                @RotateCameraRight.canceled += instance.OnRotateCameraRight;
                @SizeCameraUp.started += instance.OnSizeCameraUp;
                @SizeCameraUp.performed += instance.OnSizeCameraUp;
                @SizeCameraUp.canceled += instance.OnSizeCameraUp;
                @SizeCameraDown.started += instance.OnSizeCameraDown;
                @SizeCameraDown.performed += instance.OnSizeCameraDown;
                @SizeCameraDown.canceled += instance.OnSizeCameraDown;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Nextphrase.started += instance.OnNextphrase;
                @Nextphrase.performed += instance.OnNextphrase;
                @Nextphrase.canceled += instance.OnNextphrase;
                @SitDown.started += instance.OnSitDown;
                @SitDown.performed += instance.OnSitDown;
                @SitDown.canceled += instance.OnSitDown;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnGetItem(InputAction.CallbackContext context);
        void OnRotateCameraLeft(InputAction.CallbackContext context);
        void OnRotateCameraRight(InputAction.CallbackContext context);
        void OnSizeCameraUp(InputAction.CallbackContext context);
        void OnSizeCameraDown(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnNextphrase(InputAction.CallbackContext context);
        void OnSitDown(InputAction.CallbackContext context);
    }
}
